#@TYPE: Machine
#@NAME: NXP i.MX 93 Debix BMB 13 A1 with LPDDR4X
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for NXP i.MX 93 Debix BMB 13 A1 with LPDDR4X
#@MAINTAINER: John_gao <john@polyhex.net>
#
MACHINEOVERRIDES =. "imx93-11x11-lpddr4x-evk:"

require conf/machine/include/imx93-evk.inc

KERNEL_DEVICETREE_BASENAME = "imx93-bmb-13-a1"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    freescale/imx93-bmb-13-a1.dtb \
 "

UBOOT_CONFIG_BASENAME = "imx93_11x11_evk"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"
