#@TYPE: Machine
#@NAME: NXP i.MX 91 Debix EMB 13 A1 with LPDDR4X
#@SOC: i.MX91
#@DESCRIPTION: Machine configuration for NXP i.MX 91 Debix EMB 13 A1 with LPDDR4X
#@MAINTAINER: John_gao <john@polyhex.net>

MACHINEOVERRIDES =. "mx91:"

require conf/machine/include/imx91-evk.inc

KERNEL_DEVICETREE_BASENAME = "imx91-emb-13-a1"

 


UBOOT_CONFIG_BASENAME = "imx91_11x11_evk"

UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG[nand] = "${UBOOT_CONFIG_BASENAME}_spinand_defconfig"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"
